apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  chart:
    spec:
      chart: ./charts/supabase
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 1h0m0s
  test:
    enable: true
    timeout: 5m
    ignoreFailures: false